### ISSUE TITLE
Error at the activation stage

### ISSUE THREAD

**Issue by ivanp84** [oblakstudio/serbian-addons-for-woocommerce#10]
Error at the activation stage. I tried with various combinations of the WordPress and Woo versions. Debug message:

`Fatal error: Uncaught TypeError: ftp_fget(): Argument #1 ($ftp) must be of type FTP\Connection, null given in /opt/lampp/htdocs/wordpress_644/wp-admin/includes/class-wp-filesystem-ftpext.php:146 Stack trace: #0 /opt/lampp/htdocs/wordpress_644/wp-admin/includes/class-wp-filesystem-ftpext.php(146): ftp_fget(NULL, Resource id #1178, '/opt/lampp/htdo...', 2) #1 /opt/lampp/htdocs/wordpress_644/wp-content/plugins/serbian-addons-for-woocommerce/vendor/oblak/wp-asset-loader/src/Asset_Manifest.php(79): WP_Filesystem_FTPext->get_contents('/opt/lampp/htdo...') #2 /opt/lampp/htdocs/wordpress_644/wp-content/plugins/serbian-addons-for-woocommerce/vendor/oblak/wp-asset-loader/src/Asset_Manifest.php(62): Oblak\WP\Asset_Manifest->create_manifest_php('/opt/lampp/htdo...', '/opt/lampp/htdo...') #3 /opt/lampp/htdocs/wordpress_644/wp-content/plugins/serbian-addons-for-woocommerce/vendor/oblak/wp-asset-loader/src/Asset_Manifest.php(44): Oblak\WP\Asset_Manifest->load_manifest('/opt/lampp/htdo...') #4 /opt/lampp/htdocs/wordpress_644/wp-content/plugins/serbian-addons-for-woocommerce/vendor/oblak/wp-asset-loader/src/Asset_Loader.php(77): Oblak\WP\Asset_Manifest->__construct('/opt/lampp/htdo...', 'http://localhos...', '/opt/lampp/htdo...') #5 /opt/lampp/htdocs/wordpress_644/wp-content/plugins/serbian-addons-for-woocommerce/vendor/oblak/wp-asset-loader/src/Loader_Trait.php(29): Oblak\WP\Asset_Loader->register_namespace('wcrs', Array) #6 /opt/lampp/htdocs/wordpress_644/wp-includes/class-wp-hook.php(324): Oblak\WooCommerce\Serbian_Addons\Serbian_WooCommerce->Oblak\WP\{closure}('') #7 /opt/lampp/htdocs/wordpress_644/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #8 /opt/lampp/htdocs/wordpress_644/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #9 /opt/lampp/htdocs/wordpress_644/wp-settings.php(643): do_action('init') #10 /opt/lampp/htdocs/wordpress_644/wp-config.php(99): require_once('/opt/lampp/htdo...') #11 /opt/lampp/htdocs/wordpress_644/wp-load.php(50): require_once('/opt/lampp/htdo...') #12 /opt/lampp/htdocs/wordpress_644/wp-admin/admin.php(34): require_once('/opt/lampp/htdo...') #13 /opt/lampp/htdocs/wordpress_644/wp-admin/plugins.php(10): require_once('/opt/lampp/htdo...') #14 {main} thrown in /opt/lampp/htdocs/wordpress_644/wp-admin/includes/class-wp-filesystem-ftpext.php on line 146`
Постоји критична грешка на вашем веб месту. Молимо вас да проверите сандуче своје управљачке е-поште за упутства.

[Сазнајте више о отклањању грешака Вордпресу.](https://wordpress.org/documentation/article/faq-troubleshooting/)

**Comment by seebeen** [comment]
Fixed in 3.8.0
