### ISSUE TITLE
latest update version 3.7.1 - critical error

### ISSUE THREAD

**Issue by vpseuro** [oblakstudio/serbian-addons-for-woocommerce#13]
WordPress version 6.6.2 

 Current plugin: Serbian Addons for WooCommerce (version 3.7.1)
  PHP version 8.1.2-1ubuntu2.18 
  
  Error Details ============= An error of type E_ERROR was caused in line 19 of the file /var/www/html/wp-content/plugins/serbian-addons-for-woocommerce/lib/Serbian_WooCommerce.php. Error message: Trait "Oblak\WP\Traits\Singleton" not found

**Comment by seebeen** [comment]
Fixed in version 3.8.0

**Comment by vpseuro** [comment]
thanks
